### ISSUE TITLE
Minecraft client attempts to migrate Bukkit worlds

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeCommon#400] opened 2016-01-04 22:05 UTC
(It doesn't cause a crash, but I'd like to keep stack traces out of the log.)

```
[16:03:47] [Server thread/INFO] [Sponge]: Checking for worlds that need to be migrated...
[16:03:47] [Server thread/INFO] [Sponge]: Migrating [world] from [.].
[16:03:47] [Server thread/WARN] [Sponge]: Failed to migrate [world] from [.] to [Sponge Test Hardcore].
java.io.FileNotFoundException: .\world (Access is denied)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_66]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_66]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_66]
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:126) ~[guava-17.0.jar:?]
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:116) ~[guava-17.0.jar:?]
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:254) ~[guava-17.0.jar:?]
	at com.google.common.io.Files.copy(Files.java:442) ~[guava-17.0.jar:?]
	at com.google.common.io.Files.move(Files.java:667) ~[guava-17.0.jar:?]
	at org.spongepowered.common.world.WorldMigrator.migrateWorldsTo(WorldMigrator.java:98) [WorldMigrator.class:?]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:328) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:56) [IntegratedServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.startServer(IntegratedServer.java:130) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:500) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by Zidane** [comment] 2016-01-04 22:12
Thanks for testing it...looks like I missed something.

I'll get on it.

**Comment by Zidane** [comment] 2016-01-12 01:18
Fixed in latest commit to SpongeCommon.

**Comment by Zidane** [comment] 2016-01-12 01:18
By the way, it is by design for the client to migrate too...incase you want to load Bukkit world into SSP.

You'll still need a world management plugin to load them.

**Closed by Zidane** 2016-01-12 01:18 UTC
