### ISSUE TITLE
Water buckets are created even when BlockChange events are cancelled

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#629] opened 2016-04-03 02:22 UTC
If a player attempts to fill a bucket, and the corresponding BlockChangeEvent on the water, is cancelled, the block will not change, however, the player's bucket will still be filled with water.

**Comment by TheRaspPie** [comment] 2016-04-12 19:10
Can't reproduce in SpongeVanilla build 293.

**Comment by Zidane** [comment] 2016-06-06 06:03
Closing unless @DarkArc can reproduce.

**Closed by Zidane** 2016-06-06 06:03 UTC
Labels: bug
