### ISSUE TITLE
Add ability to have plugins exist in a directory besides /mods

### ISSUE THREAD

**Issue by DMahalko** [SpongePowered/SpongeCommon#427] opened 2016-01-13 17:24 UTC
Mumfrey wants me to post these things here rather than on the main forums. So. As I have already discussed here: 
https://forums.spongepowered.org/t/omg-youre-getting-rid-of-plugins/10689/49

The file/directory locations and launch mechanism changes for this Sponge project vs what came before seem to have been largely unnecessary. 

Yes, Sponge is a mod. So what? Both MCPC and Cauldron were mods too, and they worked just fine as a launch wrapper loading before Forge.

The semantic argument for these drastic changes vs Cauldron does not hold any water for me, if it introduces unnecessary complexities for modpack server admins.

So how much work would it take, to go back to the old Cauldron directory structure, so that ONLY modpack data occupies /mods and /config, to once again allow extremely easy delete and replace modpack upgrades?

**Comment by Zidane** [comment] 2016-01-13 18:08
Changing your title as, unlike you like to imply, there is no conspiracy here against providing the option of a plugins directory.

Regardless of what you may think, we've heard your feedback and will act upon it. Mumfrey has said this and now you have confirmation from a Sponge Leader. Be patient.

**Comment by Zidane** [comment] 2016-01-13 18:11
```
Yes, Sponge is a mod. So what? Both MCPC and Cauldron were mods too, and they worked just fine as a launch wrapper loading before Forge.
```
A mod is defined by the mechanism loading it. Cauldron wasn't loaded by FML, it was just a file modification of the game. SpongeForge is different...without Forge SpongeForge will **never be loaded**. While we'll get that plugins directory added, this part isn't changing: you install Forge and put SpongeForge in the mods directory.

**Comment by Mumfrey** [comment] 2016-01-13 18:27
I [already started working on this](https://github.com/SpongePowered/SpongeCommon/tree/feature/pluginsdir) and it works fine. Just haven't merged yet since I've been busy with other things. I will get to it when I have a spare second.

Also, I would have thought that the take-away from the forum discussion would be that being less combative is more productive. Please try to remember we're all people on the other end of the screen; we **are** on the side of server admins, and don't just make implementation decisions out of spite.

**Comment by DMahalko** [comment] 2016-01-13 19:35
I'm talking about full separation as it was before, including moving sponge out of the mods directory completely. Is there a way to tell forge to look somewhere else for mods within Forge itself, and without involving Sponge? I am not a programmer so I cannot answer these things.

"Forge, look for additional mods during startup in here:"  /root/Sponge/ 
Put sponge.mod in /root/Sponge/Sponge.mod

**Comment by kenzierocks** [comment] 2016-01-13 19:36
No, forge does not support that. The required information is inside the Sponge mod. You would need some mod to tell forge that.

**Comment by DMahalko** [comment] 2016-01-13 19:41
In the old system where Cauldron was launched first, how did Forge know where/when to inject Cauldron's mods? Is it possible to do that again? Is Forge itself significantly changed from the 1.7 days to now, that the old launch Sponge first model is now impossible?

**Comment by Aaron1011** [comment] 2016-01-13 19:51
@DMahalko: You keep referencing 'the old system', and 'how it was before'. I wanted to clear something up:

While some of the Sponge developers have worked on projects such as Cauldron before, Sponge is a new, separate project - it's not a "successor" in any sense. Things like using the `mods` dir for both plugins and mods are *not* the result of a deliberate decision to do things differently than other projects. Rather, it's the result of the fact that Forge/FML treats plugins like mods, for the most part. Differences between the handling of plugin and mods are usually the result of deliberate action by Sponge, not inaction.

**Comment by Mumfrey** [comment] 2016-01-13 19:58
> I'm talking about full separation as it was before, including moving sponge out of the mods directory completely. Is there a way to tell forge to look somewhere else for mods within Forge itself, and without involving Sponge? I am not a programmer so I cannot answer these things.
> 
> "Forge, look for additional mods during startup in here:" /root/Sponge/
> Put sponge.mod in /root/Sponge/Sponge.mod

I already pointed out on the forum thread that yes, you can put mods wherever you like and specify them to forge on the command line. In your scenario, you can put the sponge jar wherever you want and load it explicitly. Since this is already supported natively by FML, we won't be altering this behaviour.

> In the old system where Cauldron was launched first, how did Forge know where/when to inject Cauldron's mods? Is it possible to do that again? Is Forge itself significantly changed from the 1.7 days to now, that the old launch Sponge first model is now impossible?

I'm going to keep saying this until it sinks in: I **[already wrote functionality to do this but it's not merged yet](https://github.com/SpongePowered/SpongeCommon/commit/b4bc198b268083617accff113186333684283016). Since it was already agreed several days ago that this would be added, I honestly **do not understand what the problem is**???

**Comment by kenzierocks** [comment] 2016-01-13 19:58
In the old system, Cauldron was the server, so it was in charge of everything, and did not use Forge for loading plugins. Now, Forge is the server, and it is in charge of everything, including loading plugins. This is a decision that was made long ago and is not likely to change.


N.B.: Obviously none of this applies to SpongeVanilla. That should prove easier to change.

**Comment by DMahalko** [comment] 2016-01-13 20:01
Mumfrey: Ah, I did not realize you were talking about being able to move the Sponge.mod itself. I thought that discussion was in regard to moving the PLUGINs for Sponge to another location so Forge can still find them.

**Comment by Mumfrey** [comment] 2016-01-13 20:04
> Mumfrey: Ah, I did not realize you were talking about being able to move the Sponge.mod itself. I thought that discussion was in regard to moving the PLUGINs for Sponge to another location so Forge can still find them.

I showed you the other day on the forum thread that moving mods elsewhere is already fully supported by FML, you just have to specify them explicitly using the `--mods` command line argument or use the maven-style declaration. What you **can't** do is add extra "search locations" (such as the `mods` folder) where jars can be indiscriminately dumped and automatically loaded.

So, if you *don't* want to put the `sponge` jar in the `mods` folder, the simplest solution is just load it on the command line, then with the feature I've added which gives you a configurable `plugins` folder as an **additional** search location (`mods` is still processed as normal) you dump all your plugin jars nice and separate from your mods and Robert is your father's brother.

**Comment by DMahalko** [comment] 2016-01-13 20:06
Okay. So, in summary, full isolation will now be possible?

/root/minecraft.jar
/root/Forge.jar
/root/Sponge/Sponge-1.0-RELEASE.jar
/root/Sponge/Sponge.cfg
/root/Sponge/plugins/
/root/Sponge/plugin-configs/

**Comment by Mumfrey** [comment] 2016-01-13 20:06
For the record, this isn't ever going to be "the same as Bukkit", because this isn't Bukkit. However what it **does** provide, is a nice clean separation for those that want it, and the time-honoured "dump everything in `mods` for those who don't. There is just no distance in doing things the way Bukkit did because it had its own collection of problems and we - by virtue of starting a whole new project - have an opportunity to correct that.

**Comment by Mumfrey** [comment] 2016-01-13 20:09
> /root/Sponge/plugin-configs/

Plugin configs go in sub-folders under `config`, there's not really any organisational issue with that so creating a new folder just seems redundant. Configs are intrinsically easier to organise as they're much less volatile in nature than mods. It's also a bit late in the day to change this one since it's not an **additive** change (like adding the extra search folder) and thus can't be made backward compatible.

The argument for moving the configs just isn't as compelling as the one for adding an extra `plugins` search folder.

**Comment by Mumfrey** [comment] 2016-01-13 20:10
Oh and further, there's still absolutely nothing stopping you using the maven-style layout for both mods **and** plugins, which would be superior to pretty much all other solutions full stop, so there's that.

**Comment by Zidane** [comment] 2016-01-13 20:11
I also want to point out that SpongeForge will always go into **mods**. It is a mod, it is loaded by Forge, it is not a wrapper like Cauldron was.

**Comment by Mumfrey** [comment] 2016-01-13 20:12
> I also want to point out that SpongeForge will always go into mods.

It doesn't have to though, that's the point. If you specify it on the command line it can go literally anywhere you want.

**Comment by Zidane** [comment] 2016-01-13 20:12
@Mumfrey 

There was no discussion changing where SpongeForge is installed. We only discussed where **plugins** go.

That is another but related issue altogether.

**Comment by Mumfrey** [comment] 2016-01-13 20:13
> @Mumfrey
> 
> There was no discussion changing where SpongeForge is installed. We only discussed where plugins go.
> 
> That is another but related issue altogether.

This isn't up to us, it's just built right into FML, no changes are required. If someone wants to put the SpongeForge jar somewhere else, they can.

**Comment by Zidane** [comment] 2016-01-13 20:14
@Mumfrey 

Ah, completely forgot about that. Great point! Can you put the line here to specify it so @DMahalko can use that to put SpongeForge where-ever he wants?

**Comment by Mumfrey** [comment] 2016-01-13 20:15
All the docs are available here: https://github.com/MinecraftForge/FML/wiki/New-JSON-Modlist-format This includes details on the maven-style mod format.

**Comment by progwml6** [comment] 2016-01-13 20:15
we might want to put some info on that format on our docs site

**Comment by DMahalko** [comment] 2016-01-13 20:17
The compelling reason for separating plugin configs from mod configs is that when you do modpack upgrades the best thing to do is nuke /config from orbit and install the new one from the modpack upgrade.

Which I explained here:
https://forums.spongepowered.org/t/omg-youre-getting-rid-of-plugins/10689/47

We cannot simply nuke /config if we now have to pick through 30 plugin config subdirectories mixed in with the mod configs.

**Comment by Mumfrey** [comment] 2016-01-13 20:18
> We cannot simply nuke /config if we now have to pick through 30 plugin config subdirectories mixed in with the mod configs.

I'm pretty sure the plugin configs just go under `/config/Sponge` though, so it's only one folder. I don't see the issue with that.

**Comment by Zidane** [comment] 2016-01-13 20:19
``
/config/sponge/my_plugin
``

Unless a mod is now putting their configs under ``sponge`` subdirectory, you should be fine :P

**Comment by DMahalko** [comment] 2016-01-13 20:20
Why not /config-Sponge though? Or /Sponge/config? How seriously painful is that to implement?

How do plugins know where to put their configs? Do they do that directly themselves following a spec, or is Sponge telling them that when it loads them?

**Comment by Aaron1011** [comment] 2016-01-13 20:22
@DMahalko: Plugins can use a number of different annotations with a Guice injection (such as `DefaultConfig`, `ConfigDir`, or `ConfigRoot`). Sponge's guice module provides the config location for the plugin being injected into.

**Comment by Mumfrey** [comment] 2016-01-13 20:23
> Why not /config-Sponge though? Or /Sponge/config? How seriously painful is that to implement?
> 
> How do plugins know where to put their configs? Do they do that directly themselves following a spec, or is Sponge telling them that when it loads them?

They specify it when declaring their configuration in the plugin. Honestly it's one folder under `config`, I don't see an update workflow that can't include a single folder under `config` being a simple case to deal with. `config` is a universal standard and it makes sense to adopt it.

**Comment by DMahalko** [comment] 2016-01-13 20:32
It makes management easier for server admins, having all these things separated. Not everyone setting up servers is a programming or operation system professional. Often it's some 12 year old trying to throw something together, with some help from someone else. The less complicated it is for them to deal with modpack upgrades, the easier life will be for everyone.

And anyway I'm not asking you to change it as the default location for plugin configs. I am just asking that you make it CONFIGURABLE by server admins, with an optional entry in the sponge.cfg.

**Comment by Zidane** [comment] 2016-01-13 20:35
@DMahalko 

Now THAT is a reason for it (not the combative attitude yet again). I see no reason we couldn't let you set the config root to a folder of your choosing for plugins. Sponge's configs itself would still go into ```/config/sponge``` FYI.

**Comment by Mumfrey** [comment] 2016-01-13 20:35
@Zidane +1

**Comment by kenzierocks** [comment] 2016-01-13 20:35
1) Copy `config/sponge/` out.
2) Nuke `config/`.
3) Create `config/`.
4) Copy `config/sponge/` in.


Is this too hard?

**Comment by DMahalko** [comment] 2016-01-13 20:36
*facedesk*  Okay, make this a command line option for sponge.jar then

**Comment by Mumfrey** [comment] 2016-01-13 20:37
`sponge.jar` is still a forge *mod* though, so it makes sense that its config goes with the rest of the forge mod configs.

**Comment by DMahalko** [comment] 2016-01-13 20:48
Is there not some simple way to make this work easily to have optional full isolation?

Code:
IF a sponge.cfg is found in /root/sponge  use it.
Otherwise look for it in /root/config/sponge/ as usual.
If it doesn't exist, create /root/config/sponge/ as usual, and write the default config.

To enable alternate functionality the admin merely needs to do this after first run of Sponge:
Move /root/config/sponge   /root/.

**Comment by Tzky** [comment] 2016-01-13 20:49
Asking for the Docs:

* We will support relocating/using an alternate ``/plugin`` folder?
* We will support relocating/using an alternate ``/config`` folder for plugins?
* Relocation of sponge.jar is already possible via FML?

@DMahalko 
That should be a Forge issue as SpongeForge still is "just" a Forge Coremod.

**Comment by DMahalko** [comment] 2016-01-13 21:00
1 /root/minecraft.jar
2 /root/Forge.jar
3 /root/Sponge/Sponge-1.0-RELEASE.jar
4 /root/Sponge/Sponge.cfg
5 /root/Sponge/plugins/
6 /root/Sponge/plugin-configs/

No 3 - Alternate single mod location specified via forge command line
No 4 - Alternate path via sponge.jar looking for its own config at startup
No 5 - Specified in Sponge.cfg or this alt location is auto-used if found
No 6 - Specified in Sponge.cfg or this alt location is auto-used if found

**Comment by kenzierocks** [comment] 2016-01-13 21:10
Forge mandates the location of mod configs.

**Comment by bloodmc** [comment] 2016-01-13 21:21
SpongeForge is a forge core mod which can run on BOTH client and server. The config belongs where it is. Stop trying to relate it to MCPC/Cauldron.

**Comment by Mumfrey** [comment] 2016-01-13 21:37
And so spaketh the actual *author* of Cauldron :smile: 

Summary on this issue:

* I will add the configurable additional `plugins` dir as mentioned above, this basically just needs merging anyway.
* I will make the base shared config dir for plugins configurable in the same way as per @Zidane's suggestion above.
* Sponge config stays where it is because it's simple, deterministic, in keeping with general policy for mods and the argument for relocating it just simply isn't strong enough to overcome the advantages (standardisation, etc.) of leaving it where it belongs.
* Pretty much everything else is achievable via the `--mods` command line argument so we can liaise with @tzky and @Inscrutable on getting that added to our docs

**Closed** 2016-06-23 17:41 UTC
Labels: accepted, enhancement
