### ISSUE TITLE
Incomplete information in EntitySpawnEvent to distinguish..

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#598] opened 2016-03-18 10:08 UTC
See image attached for event.toString() printouts for events involving spawning tests involving Silverfish and Spiders as just two examples.

It seems that naturally-spawning mobs appearing at night, etc, will appear different only in that the spongetype is WorldSpawner (and they are .Spawner subevents).  But spawned via the speckled eggs, or the flaming mobspawner cubes, there is no distinction.  Silverfish released from monster-block stoneblocks show cause as "AdditionalSource" to identify that a player has broken the block, but in no case is the user who uses a mob egg identified, nor the event tagged as such.
As for spawning via a flamer-cube, it would really be nice to have that information in the cause to identify this special spawning origin; the only difference I can spot between it and otherwise is the multidecimal place position value in the cause.
Also, the SpawnType is "Custom/Custom" in multiple cases, is this intentional for these events, or a missing value to be filled in, as "SpawnerCube" would be nicer than "Custom" cause-type.

![spawnomolies](https://cloud.githubusercontent.com/assets/3393225/13874688/d5590230-eccf-11e5-84f5-afca2e89192d.png)

**Comment by ryantheleach** [comment] 2016-03-18 13:52
For what it's worth I think it's possible that the positions recorded are those positions in minecraft. the positions that silverfish from eggs are spawned where the player interacts with a block. but the flame cube positions are based on random ranges which could be the reason for seeing the differences in position.

**Comment by theboomer** [comment] 2016-03-19 04:17
It might also turn out that the CAUSE for the "EntityConstructEvent" and sub-events might be the more useful - as those events are single-entity pre-spawn and cancellable easily, instead of getting an event with 17 spawn-events in it, and having to flip through each of them to test the coordinate precision, and removing that one transaction from the list if need be.  The EntityConstructEvent might have a CAUSE explanation for why it is about to form - summon command, natural, spawnercube,  mob egg break/use, egg break/use, breeding (and all the non living entity reasons as well)

However, the EntityConstructEvent is yet another not-yet-Implimented event, so there's no saying if it would be more useful or not.

Either way, is "CUSTOM" really an appropriate Cause for these vanilla-minecraft specific behaviors in this method?  And why would not the owner of the mob egg be recorded in the cause as well? (or a dispenser, dropper etc that utilized it?)

**Comment by gabizou** [comment] 2016-03-19 04:50
Currently, the system is somewhat functional for the basics, but nonfunctional beyond what it was designed for. I can assure you that when #502 is merged, it'll have much cleaner implementation/usage than currently available. I'll take a look at possibly cleaning up the current implementation, unless @Zidane wishes the refactor to get merged sooner than later.

**Comment by Zidane** [comment] 2016-04-22 00:19
This is closed in 1.9.

**Closed by Zidane** 2016-04-22 00:19 UTC
