### ISSUE TITLE
Sneak placing doesn't work

### ISSUE THREAD

**Issue by cindylo** [SpongePowered/SpongeCommon#750] opened 2016-05-27 19:46 UTC
Sneaking and placing a block on SpongeVanilla bleeding build 30 and 31 straight up doesn't work. It disappears instantly as if you're in a protected region with no permission to place it. But if you're in survival it does pull it from your inventory.

**Comment by gabizou** [comment] 2016-05-27 20:09
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/745

**Closed by gabizou** 2016-05-27 20:09 UTC
