### ISSUE TITLE
Can't approach the edge of the world without crashing

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#762] opened 2016-06-01 07:35 UTC
Granted, generation isn't supposed to work at that point, but Vanilla is able to currently handle going to the edge of the world without crashing:

```
[00:26:06] [Client thread/INFO]: [CHAT] Teleported gabizou to 2.99999505E7, 100.0, 2.99999505E7
[00:26:06] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception generating new chunk
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:772) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159) ~[IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: Chunk coordinates are not valid1875000, 1874993
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[guava-17.0.jar:?]
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:63) ~[ChunkPrimerBuffer.class:?]
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:57) ~[ChunkPrimerBuffer.class:?]
    at org.spongepowered.common.world.gen.SpongeChunkProvider.provideChunk(SpongeChunkProvider.java:222) ~[SpongeChunkProvider.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172) ~[ChunkProviderServer.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:132) ~[ChunkProviderServer.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:102) ~[ChunkProviderServer.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:203) ~[ChunkProviderServer.class:?]
    at net.minecraft.world.World.getChunkFromChunkCoords(World.java:336) ~[World.class:?]
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:377) ~[WorldServer.class:?]
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227) ~[WorldServer.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:766) ~[MinecraftServer.class:?]
    ... 4 more
[00:26:06] [Server thread/ERROR]: This crash report has been saved to: /Tools/Sponge/1.8.9/SpongeForge/run/./crash-reports/crash-2016-06-01_00.26.06-server.txt
[00:26:06] [Server thread/INFO]: Stopping server
[00:26:06] [Server thread/INFO]: Saving players
[00:26:06] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:612]: ---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/1/16 12:26 AM
Description: Exception generating new chunk

java.lang.IllegalArgumentException: Chunk coordinates are not valid1875000, 1874993
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:63)
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:57)
    at org.spongepowered.common.world.gen.SpongeChunkProvider.provideChunk(SpongeChunkProvider.java:222)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:132)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:102)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:203)
    at net.minecraft.world.World.getChunkFromChunkCoords(World.java:336)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:377)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:766)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:63)
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:57)
    at org.spongepowered.common.world.gen.SpongeChunkProvider.provideChunk(SpongeChunkProvider.java:222)

-- Chunk to be generated --
Details:
    Location: 1875000,1874993
    Position hash: 8053033617103928
    Generator: RandomLevelSource
Stacktrace:
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:132)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:102)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:203)
    at net.minecraft.world.World.getChunkFromChunkCoords(World.java:336)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:377)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)

-- Affected level --
Details:
    Level name: New World4535
    All players: 1 total; [EntityPlayerMP['gabizou'/503, l='New World4535', x=29999950.50, y=100.00, z=29999950.50]]
    Chunk stats: ServerChunkCache: 834 Drop: 0
    Level seed: -2061549484377213235
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: -48.00,64.00,256.00 - World: (-48,64,256), Chunk: (at 0,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 41453 game time, 1102 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 31695 (now: false), thunder time: 102815 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:766)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Mac OS X (x86_64) version 10.11.5
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1352508648 bytes (1289 MB) / 2826960896 bytes (2696 MB) up to 7635730432 bytes (7282 MB)
    JVM Flags: 0 total; 
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1890 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8.9-11.15.1.1890-1.8.9-PROJECT(SpongeForge).jar) 
    UCHIJAAAA   Forge{11.15.1.1890} [Minecraft Forge] (forgeSrc-1.8.9-11.15.1.1890-1.8.9-PROJECT(SpongeForge).jar) 
    UCHIJAAAA   sponge{$version} [SpongeForge] (SpongeForge_java6) 
    Loaded coremods (and transformers): 
SpongeCoremod (unknown)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['gabizou'/503, l='New World4535', x=29999950.50, y=100.00, z=29999950.50]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge,sponge'
```

Yes, this was in a dev environment, but none the less, I thought I'd give it a shot to do some experiments.

**Comment by stephan-gh** [comment] 2017-05-07 17:00
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/651

**Closed by stephan-gh** 2017-05-07 17:00 UTC
Labels: system: world, type: duplicate
