### ISSUE TITLE
[1.12.2] Several incorrect SpawnTypes for various entity-spawn events 

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#920] opened 2016-09-04 15:28 UTC
First, thank you for fixing the few examples that were listed in my previous post as promptly as was done after the push earlier. #916
I have tested _nearly every_ spawn-event scenario possible I can imagine and discovered many are incorrect results or not assigned, and some that require a double-check to see if they are consistent with their result planned definition because I am not sure.

System: Forge-2073 + SpongeForge-2073---1.10.2-Beta-1698
No mods or plugins, vanilla clients only;  One plugin to log spawnevent information only.

```

Spawning System                             Reports As          Should be
--------------------------------------------------------------------------
Player places armor stand                    SpawnEgg            Placement
Player places item frame                     SpawnEgg            Placement
Player places pictureframe                   SpawnEgg            Placement
Player placing any minecart on track         SpawnEgg            Placement
Experience orbs from killing mobs            Custom              Experience
Experience from catching fish                Placement           Experience
Experience orbs from mining ores(coal,       Placement           Experience      
  lapis, redstone, diamond, emerald, quartz)

```

Note that XPOrbs spawned from breeding-births and xp-bottle explosions do return "**Experience**", but not from these above scenarios.  Also, we were UNABLE to get furnaces to generate XP at all in testing, something I am going to investigate further now to see if it was a human-tester error (not likely, replicating a control test) or sponge, or forge, or vanilla, so I do not know what SMELTING XP orb spawning would be returning, and will report as a separate issue pending information learned.

```
For the following, I expect/suspect that they should be throwing "Projectile" 
- Throwing a bottle of enchanting  ---- currently returns "Placement"
- Throwing a splash/linger potion ----- currently returns "Placement"
- Throwing a snowball ----------------- currently returns "Placement"

```

Placing a block of sand / gravel / anvil etc   -- currently throws **BlockSpawning**, but there is a **FallingBlock** type unused.   This may be a matter of overplanning the return-list originally, before refining the result - Is **BlockSpawning** intended for this, or was **FallingBlock** intended, or does **FallingBlock** have a different intent as a type than this?   The fact that the **BlockSpawning** contains a falling-block entity in the event makes it unambiguous either way, so this is just a sanity-check against the intent being asked of for this scenario.

Using the /give command  ----- currently returns   **CustomType** ...   I do not know which might be preferred, but dont think that **CustomType** is intended for any vanilla-system behavior, but reserved for other things 'custom' if I understand correctly.

Fishing rod casting ----------- currently returns **Placement**.   This indeed does make sense, but seemed worthy of noting for verification
# 

Despite being an entity it is noted that there is NO spawn event caught at all when a LeashKnot is spawned by attaching a roped mob to a post.  There IS a "**CustomType**" caught if a LeashKnot is summoned to appear 

There is also NO spawn event caught at all when a **LightningBolt** is summoned, or when created by the environment - however this is likely very intentional as the Lightning is given special treatment as its own thing.

_I Did NOT test Endworld based entities due to my unfamiliarity with End world environment, mechanics and expectations, so these cases will make up some of the very few scenarios not observed._

**Comment by Aaron1011** [comment] 2016-09-04 15:53
@theboomer: Thanks for all of your hard work finding these bugs!

**Comment by theboomer** [comment] 2016-09-04 16:05
I can't fix 'em, but I can try to get as much info to those who can when I find 'em :)
I know my limitations fall just on this side of the point of filing PRs

**Comment by lesbleu** [comment] 2017-07-16 18:44
This bug is still present in 1.12 (SpongeVanilla 1.12 Beta 300).

**Comment by gabizou** [comment] 2018-01-10 05:40
Just double checked current code, since I'm positive the cause refactor and multiple cause tracker refactors, this issue can now be closed. Verified the cases listed at the top of the issue, they are exactly as they should be (in the expected results column).

**Comment by ImMorpheus** [comment] 2018-01-11 17:47
This should be reopened.

I thought 1688 could be closed so I was testing a few things:

First:

```
Player places armor stand                
Player places item frame                    
Player places pictureframe                  
Player placing any minecart on track         
```

are indeed fixed. However things are different for exp related spawntypes (and a few other cases):

Test plugin: 

```
    @Listener
    public void onSpawn(SpawnEntityEvent event) {
        Optional<SpawnType> s = event.getCause().getContext().get(EventContextKeys.SPAWN_TYPE);
        //avoid spam
        if (s.isPresent() && !s.get().equals(SpawnTypes.WORLD_SPAWNER) && !s.get().equals(SpawnTypes.CHUNK_LOAD)) {
            System.out.println("---------------------------------");
            for (Entity e : event.getEntities()) {
                if (e.getType().equals(EntityTypes.EXPERIENCE_ORB)) {
                    System.out.println("FOUND ORBS: "+event.getCause().getContext().get(EventContextKeys.SPAWN_TYPE).get().getName());
                }
            }
            System.out.println(event.getCause());
            System.out.println("---------------------------------");
        }
    }
```

Experience orbs from killing mobs:

```
[16:46:24 INFO] [STDOUT]: ---------------------------------
[16:46:24 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], Stack={EntitySpider['Spider'/616, l='world', x=48.06, y=89.00, z=-115.03], EntityDamageSource{Name=player, Type=attack, Source=EntityPlayerMP['jeb_'/153, l='world', x=48.69, y=90.28, z=-115.05]}, EntitySpider['Spider'/616, l='world', x=48.06, y=89.00, z=-115.03], EntityPlayerMP['jeb_'/153, l='world', x=48.69, y=90.28, z=-115.05]}]
[17:46:24 INFO] [STDOUT]: ---------------------------------
```

Experience from catching fish:

```
[16:49:54 INFO] [STDOUT]: ---------------------------------
[16:49:54 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:placement, name=Placement}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=81.82, y=63.00, z=-66.77], "sponge:used_item"=SpongeItemStackSnapshot{itemType=ItemFishingRod{Name=fishingRod}, quantity=1}, "sponge:notifier"=EntityPlayerMP['jeb_'/153, l='world', x=81.82, y=63.00, z=-66.77]], Stack={EntityPlayerMP['jeb_'/153, l='world', x=81.82, y=63.00, z=-66.77]}]
[16:49:54 INFO] [STDOUT]: ---------------------------------
[16:49:54 INFO] [STDOUT]: ---------------------------------
[16:49:54 INFO] [STDOUT]: FOUND ORBS: Placement
[16:49:54 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:placement, name=Placement}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=81.82, y=63.00, z=-66.77], "sponge:used_item"=SpongeItemStackSnapshot{itemType=ItemFishingRod{Name=fishingRod}, quantity=1}, "sponge:notifier"=EntityPlayerMP['jeb_'/153, l='world', x=81.82, y=63.00, z=-66.77]], Stack={EntityPlayerMP['jeb_'/153, l='world', x=81.82, y=63.00, z=-66.77]}]
[16:49:54 INFO] [STDOUT]: ---------------------------------
```

Experience orbs from mining ores:
```
[16:53:00 INFO] [STDOUT]: ---------------------------------
[16:53:00 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=69.96, y=66.00, z=-62.82], "sponge:used_item"=SpongeItemStackSnapshot{itemType=ItemPickaxe{Name=pickaxeDiamond}, quantity=1}, "sponge:notifier"=EntityPlayerMP['jeb_'/153, l='world', x=69.96, y=66.00, z=-62.82]], Stack={SpongeBlockSnapshot{worldUniqueId=c5f0f4fc-8efd-4b89-a3fc-7d31e889d22d, position=(70, 66, -59), blockState=minecraft:diamond_ore, extendedState=minecraft:diamond_ore}, EntityPlayerMP['jeb_'/153, l='world', x=69.96, y=66.00, z=-62.82]}]
[16:53:00 INFO] [STDOUT]: ---------------------------------
[16:53:00 INFO] [STDOUT]: ---------------------------------
[16:53:00 INFO] [STDOUT]: FOUND ORBS: DroppedItem
[16:53:00 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}, "sponge:used_item"=SpongeItemStackSnapshot{itemType=ItemPickaxe{Name=pickaxeDiamond}, quantity=1}], Stack={EntityPlayerMP['jeb_'/153, l='world', x=69.96, y=66.00, z=-62.82]}]
[16:53:00 INFO] [STDOUT]: ---------------------------------

```

Experience orbs from smelting ores:
There is something wrong with smelting 

Throwing a bottle of enchanting:

```
[17:23:56 INFO] [STDOUT]: ---------------------------------
[17:23:56 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:placement, name=Placement}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=62.74, y=74.24, z=-61.72], "sponge:used_item"=SpongeItemStackSnapshot{itemType=ItemExpBottle{Name=expBottle}, quantity=64}, "sponge:notifier"=EntityPlayerMP['jeb_'/153, l='world', x=62.74, y=74.24, z=-61.72]], Stack={EntityPlayerMP['jeb_'/153, l='world', x=62.74, y=74.24, z=-61.72]}]
[17:23:56 INFO] [STDOUT]: ---------------------------------
[17:23:56 INFO] [STDOUT]: ---------------------------------
[17:23:56 INFO] [STDOUT]: FOUND ORBS: Experience
[17:23:56 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:experience, name=Experience}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=62.74, y=74.24, z=-61.72]], Stack={EntityExpBottle['entity.ThrownExpBottle.name'/5540, l='world', x=65.18, y=67.73, z=-61.03]}]
[17:23:56 INFO] [STDOUT]: ---------------------------------
```

Throwing a splash/linger potion:
```
[17:25:36 INFO] [STDOUT]: ---------------------------------
[17:25:36 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:placement, name=Placement}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=63.17, y=74.37, z=-61.09], "sponge:used_item"=SpongeItemStackSnapshot{itemType=ItemLingeringPotion{Name=lingering_potion}, quantity=1}, "sponge:notifier"=EntityPlayerMP['jeb_'/153, l='world', x=63.17, y=74.37, z=-61.09]], Stack={EntityPlayerMP['jeb_'/153, l='world', x=63.17, y=74.37, z=-61.09]}]
[17:25:36 INFO] [STDOUT]: ---------------------------------
[17:25:37 INFO] [STDOUT]: ---------------------------------
[17:25:37 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:passive, name=Passive}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=63.17, y=74.37, z=-61.09]], Stack={EntityPotion['Potion'/5674, l='world', x=63.15, y=67.06, z=-61.09]}]
[17:25:37 INFO] [STDOUT]: ---------------------------------
```

Throwing a snowball:
```
[17:27:47 INFO] [STDOUT]: ---------------------------------
[17:27:47 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:placement, name=Placement}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=63.17, y=74.37, z=-61.09], "sponge:used_item"=SpongeItemStackSnapshot{itemType=ItemSnowball{Name=snowball}, quantity=1}, "sponge:notifier"=EntityPlayerMP['jeb_'/153, l='world', x=63.17, y=74.37, z=-61.09]], Stack={EntityPlayerMP['jeb_'/153, l='world', x=63.17, y=74.37, z=-61.09]}]
[17:27:47 INFO] [STDOUT]: ---------------------------------
```

Placing a block of sand:
```
[17:30:01 INFO] [STDOUT]: ---------------------------------
[17:30:01 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:block_spawning, name=BlockSpawning}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=67.75, y=128.73, z=-59.95], "sponge:notifier"=EntityPlayerMP['jeb_'/153, l='world', x=67.75, y=128.73, z=-59.95]], Stack={SpongeLocatableBlock{blockState=minecraft:sand[variant=sand], position=(65, 130, -62), worldId=c5f0f4fc-8efd-4b89-a3fc-7d31e889d22d, worldReference=java.lang.ref.WeakReference@eb2845c}, WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld}}]
[17:30:01 INFO] [STDOUT]: ---------------------------------
```

Placing a block of sand on a block then breaking the block beneath it (this should be a case handled by SpawnTypes.FALLING_BLOCK):
```
[17:34:11 INFO] [STDOUT]: ---------------------------------
[17:34:11 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:block_spawning, name=BlockSpawning}, "sponge:owner"=EntityPlayerMP['jeb_'/153, l='world', x=66.90, y=112.53, z=-58.99], "sponge:notifier"=EntityPlayerMP['jeb_'/153, l='world', x=66.90, y=112.53, z=-58.99]], Stack={SpongeLocatableBlock{blockState=minecraft:sand[variant=sand], position=(65, 114, -62), worldId=c5f0f4fc-8efd-4b89-a3fc-7d31e889d22d, worldReference=java.lang.ref.WeakReference@53715f5}, WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld}}]
[17:34:11 INFO] [STDOUT]: ---------------------------------

```
/give me diamond:
```
[17:31:54 INFO] [STDOUT]: ---------------------------------
[17:31:54 INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:placement, name=Placement}], Stack={EntityPlayerMP['jeb_'/153, l='world', x=67.75, y=108.41, z=-59.95]}]
[17:31:54 INFO] [STDOUT]: ---------------------------------
```

**Comment by Zidane** [comment] 2018-01-12 04:54
@JBYoshi 

Want to take a look at this?

**Comment by Zidane** [comment] 2018-02-03 00:10
Closing as we have a PR open: https://github.com/SpongePowered/SpongeCommon/pull/1749

**Closed by Zidane** 2018-02-03 00:10 UTC
Labels: system: event, type: bug, version: 1.10 (u), version: 1.12
