### ISSUE TITLE
configurate issue

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/SpongeCommon#966] opened 2016-10-04 00:37 UTC
A file permission issue with configurate was fixed but was not pushed out to mvnrepository.com, Because of this Sponge is using a configurate version where the bug is still present.

I have opened an issue on zml2008's configurate project on github but he has still not responded or fixed the issue, I am wonder if you are able to contact him or fix this issue yourselves (By using your own build of configurate instead of the version on mvnrepository)

Cheers LXGaming

**Comment by gabizou** [comment] 2016-10-04 02:40
Duplicate of https://github.com/SpongePowered/SpongeAPI/issues/1331

**Closed by gabizou** 2016-10-04 02:40 UTC
