### ISSUE TITLE
setBlock doesn't set cause properly for ChangeBlockEvent.Break

### ISSUE THREAD

**Issue by Xenograph** [SpongePowered/SpongeCommon#428] opened 2016-01-13 19:20 UTC
The code:
```
    @Listener
    public void onBlockBreak(ChangeBlockEvent.Break e) {
        Optional<Player> maybePlayer = e.getCause().get(NamedCause.SOURCE, Player.class);
        if (maybePlayer.isPresent()) {
            logger.info(e.getCause().toString());
            logger.info("Cancelling ChangeBlockEvent");
            e.setCancelled(true);
            Vector3i pos = e.getTransactions().get(0).getOriginal().getPosition();
            Sponge.getScheduler().createTaskBuilder()
                    .execute(() -> e.getTargetWorld().setBlockType(pos, BlockTypes.AIR, true))
                    .delay(1, TimeUnit.SECONDS)
                    .submit(plugin);
        }
    }
```

Upon joining the server and breaking a single block, this is the output:
```
[14:14:08] [Server thread/INFO] [myplugin]: Cause[{Name=Source, Object={EntityPlayerMP['DougCraft'/351, l='world', x=-243.30, y=71.00, z=259.81]}}]
[14:14:08] [Server thread/INFO] [myplugin]: Cancelling ChangeBlockEvent
[14:14:10] [Server thread/INFO] [myplugin]: Cause[{Name=Source, Object={EntityPlayerMP['DougCraft'/351, l='world', x=-243.33, y=71.00, z=259.80]}}]
[14:14:10] [Server thread/INFO] [myplugin]: Cancelling ChangeBlockEvent
[14:14:11] [Server thread/INFO] [myplugin]: Cause[{Name=Source, Object={EntityPlayerMP['DougCraft'/351, l='world', x=-243.33, y=71.00, z=259.80]}}]
[14:14:11] [Server thread/INFO] [myplugin]: Cancelling ChangeBlockEvent
[14:14:12] [Server thread/INFO] [myplugin]: Cause[{Name=Source, Object={EntityPlayerMP['DougCraft'/351, l='world', x=-243.33, y=71.00, z=259.80]}}]
[14:14:12] [Server thread/INFO] [myplugin]: Cancelling ChangeBlockEvent
[14:14:13] [Server thread/INFO] [myplugin]: Cause[{Name=Source, Object={EntityPlayerMP['DougCraft'/351, l='world', x=-243.33, y=71.00, z=259.80]}}]
[14:14:13] [Server thread/INFO] [myplugin]: Cancelling ChangeBlockEvent
[14:14:14] [Server thread/INFO] [myplugin]: Cause[{Name=Source, Object={EntityPlayerMP['DougCraft'/351, l='world', x=-243.33, y=71.00, z=259.80]}}]
[14:14:14] [Server thread/INFO] [myplugin]: Cancelling ChangeBlockEvent
[14:14:15] [Server thread/INFO] [myplugin]: Cause[{Name=Source, Object={EntityPlayerMP['DougCraft'/351, l='world', x=-243.33, y=71.00, z=259.80]}}]
[14:14:15] [Server thread/INFO] [myplugin]: Cancelling ChangeBlockEvent
[14:14:16] [Server thread/INFO] [myplugin]: Cause[{Name=Source, Object={EntityPlayerMP['DougCraft'/351, l='world', x=-243.33, y=71.00, z=259.80]}}]
[14:14:16] [Server thread/INFO] [myplugin]: Cancelling ChangeBlockEvent
[14:14:17] [Server thread/INFO] [myplugin]: Cause[{Name=Source, Object={EntityPlayerMP['DougCraft'/351, l='world', x=-243.33, y=71.00, z=259.80]}}]
[14:14:17] [Server thread/INFO] [myplugin]: Cancelling ChangeBlockEvent
```
...and so on, in an infinite loop. So, for some reason calling the setBlockType method creates a ChangeBlockEvent.Break with a cause with the original player as source. The same results occurred with setBlock and Location.removeBlock. The infinite loop stops and the block finally gets destroyed if the original player disconnects from the server. Also, the infinite loop seems to randomly stop sometimes for no apparent reason (that is, the setBlock call doesn't cause an event with a player as the source), resulting in the block being destroyed.

**Comment by simon816** [comment] 2016-04-14 05:03
This seems to be caused by `PacketUtil#onProcessPacket`

When calling `setBlockType` in your code, the world is updated and the block transaction is stored in the `CauseTracker`
Nothing happens for the rest of that tick. (From what I could tell)
Meanwhile, on the network thread, the client sends some packet to the server (could be anything). The packet is added to a queue to be processed next tick.
Along comes the next tick, the packet is immediately processed (first thing in `MinecraftServer#updateTimeLightAndEntities`)
The cause tracker is then flushed with the cause of the player that sent the packet
https://github.com/SpongePowered/SpongeCommon/blob/41b03c89d6604a3cb8b6fd7e72edd212d4441d21/src/main/java/org/spongepowered/common/network/PacketUtil.java#L105-L109
Hence why it appears that the player 'caused' it

@gabizou can you confirm this is fixed with your refactor?

**Comment by Yeregorix** [comment] 2016-05-13 19:33
Hi, I have the same problem, I hope it will be solved soon

**Comment by Zidane** [comment] 2016-05-18 04:58
You need to call setBlockType/setBlock that take Cause

https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/extent/Extent.java#L220

This is important because specifying your own Cause tells the CauseTracker "Hey, don't bother with tracking this...I've got it, I've done the legwork and here is why this is happening!"

You can literally remove your scheduled task code as well, simply call the above and all should be well. Let us know otherwise.

**Closed by Zidane** 2016-05-18 04:58 UTC
