### ISSUE TITLE
Not being able to edit Command Blocks

### ISSUE THREAD

**Issue by Pymous** [SpongePowered/SpongeCommon#893] opened 2016-08-22 14:35 UTC
Hey !

Using Sponge API 5, we don't seem to be able to edit Command Blocks.

I created this issue after finding out about it, helped by other admins : https://forums.spongepowered.org/t/opening-command-blocks/14211

Server.properties are set properly :
```
enable-command-block=true
op-permission-level=2
```

Version of the API 5 affected : All of them as far as we know :)

**Comment by Minecrell** [comment] 2016-08-22 14:54
Are you using a permission plugin?

**Comment by Pymous** [comment] 2016-08-22 14:58
@Minecrell : Personally I do (PEX), but one member on the topic don't use any.

**Comment by Minecrell** [comment] 2016-08-22 15:00
I cannot reproduce this using no permission plugin, testing with a permission plugin right now.

**Comment by Minecrell** [comment] 2016-08-22 15:09
I can confirm that this happens on 1.10 when you are attempting to edit a command block while not an operator. It seems like it was not properly updated to Minecraft 1.10.

**Comment by Pymous** [comment] 2016-08-22 15:16
I should have specified 1.10.2, yup, sorry :) 

Do you know if it's a complicated issue to fix ?

**Comment by Minecrell** [comment] 2016-08-22 16:27
This will be hard since Minecraft now seems to check the command block permission in several places, as well as on the client. So if the client does not know that it is an OP (e.g. when using PermissionsEx) then it will never even open the command block GUI.

**Comment by Pymous** [comment] 2016-08-22 16:31
So PEX and Sponge need to be updated, bummer :(

**Comment by ryantheleach** [comment] 2016-08-22 16:44
Wait, so the client knows who is OP now?

**Comment by Minecrell** [comment] 2016-08-22 16:47
@ryantheleach From what I can tell the client now knows if it is an OP on the server (but not if any other player is OP).

**Comment by Pymous** [comment] 2016-08-22 16:49
I don't see the point of this modification ... just making it complicated for you guys ...

**Comment by Zidane** [comment] 2016-08-22 22:39
@Minecrell 

I wonder if the appropriate fix is to just tell the client they are OP and block these actions on the server. Even for the CommandBlock GUI, we could just force it close with a packet.

**Comment by Rasgnarok** [comment] 2016-08-23 04:25
Personally, I have this issue with PEX and SpongeForge - but before moving to 1.10.2, I was able to edit command blocks just fine (I migrated my permission files, without changing anything). Now with `1.10.2 - sf 1675` I cannot. Running PEX 1.10.2 as well.

**Comment by Bammerbom** [comment] 2016-08-23 08:19
I have this issue without PEX and with SpongeForge. This happens after I am playing for some time, I am in creative mode but I can't open any command blocks. Typing "/op Bammerbom" or relogging fixes this. I can't find a specific way to reproduce this.

**Comment by rexbut** [comment] 2016-08-25 22:15
We had already reported the problem : https://github.com/SpongePowered/SpongeCommon/issues/868

The tested permission is empty.

**Comment by Rasgnarok** [comment] 2016-09-27 17:19
@Zidane Is there any news on this? I have tried with Blood's `spongeforge-1.10.2-2079-5.0.0-BETA-async-test44.jar` and it is still an issue. I cannot open command blocks, as I could not in `1692` spongeforge.

**Comment by Aaron1011** [comment] 2016-10-08 21:54
Sorry for the super long delay. Fixed in https://github.com/SpongePowered/SpongeCommon/commit/3aaf0897f7e040f533e026df4896433d4fa80973.

**Closed by Aaron1011** 2016-10-08 21:54 UTC
Labels: 1.10, accepted, bug
