### ISSUE TITLE
No way to determine source BlockSnapshot for DropItemEvent.Destruct

### ISSUE THREAD

**Issue by Meegooo** [SpongePowered/SpongeCommon#906] opened 2016-08-27 10:11 UTC
In 1.10 this event always has AIR as a source BlockSnapshot.
http://i.imgur.com/J3RXRwy.png

And for the record, no player in the cause, so this: https://github.com/SpongePowered/SpongeCommon/issues/846

PS. In 1.8.9 it worked correctly http://i.imgur.com/DDiKIDW.png

**Comment by ImMorpheus** [comment] 2017-11-24 16:47
you again DropItemEvent ?

Duplicate of #732

**Closed** 2017-11-24 17:03 UTC
Labels: status: accepted, type: bug, version: 1.10
