### ISSUE TITLE
Vanished players pickup items, are targeted by entities

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#547] opened 2016-02-27 23:12 UTC
Using spongeforge 1167.

**Comment by gabizou** [comment] 2016-02-27 23:52
@viveleroi Is this still present in the latest SF/SV?

**Comment by viveleroi** [comment] 2016-02-27 23:54
1167 is only three builds behind and I haven't seen any commits related to this.

**Comment by gabizou** [comment] 2016-02-27 23:54
Just double checking as I don't want it to be a non-issue on master by it being somehow broken and then fixed in the commits between builds ;). I'll get to this shortly.

**Comment by gabizou** [comment] 2016-02-28 02:37
@viveleroi I can't reproduce this locally, any noticeable changes server side?

**Comment by gabizou** [comment] 2016-05-02 04:44
@viveleroi let me know if this is still an issue, otherwise I'm closing it.

**Closed by gabizou** 2016-05-02 04:44 UTC
