### ISSUE TITLE
ChangeBlockEvent.Place is Fired with Redstone Repeaters

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/SpongeCommon#726] opened 2016-05-16 22:34 UTC
Cause Dump: http://pastebin.com/qNWXHY9u
Screenshot: https://i.gyazo.com/749cb1702684e7ab7d268f928ddab6f7.jpg

Basically, the `ChangeBlockEvent.Place` event is fired for the contraption above, although I'm not sure it should be.

**Comment by modwizcode** [comment] 2016-05-16 23:29
Can you post the whole dump?

**Comment by bloodmc** [comment] 2016-05-16 23:51
Working as intended since repeaters use 2 different blocks (unpowered, powered). Filter it as you want it to be.

**Comment by Deamon5550** [comment] 2016-05-16 23:58
@bloodmc Place should be from `air -> block`, a repeater changing states should be `ChangeBlockEvent.Modify`.

**Comment by bloodmc** [comment] 2016-05-17 00:18
@Deamon5550 Modify is for changing blockstates, Place is for changing BlockTypes

**Comment by Deamon5550** [comment] 2016-05-17 01:02
@bloodmc Ah those events need their javadocs updated then because as it stands Place is for blocktypes being added to the world and Modify is for blocktypes changing in the world.

**Comment by bloodmc** [comment] 2016-05-17 01:18
@Deamon5550 Ah yes, I guess those docs could easily cause confusion. I'll make sure to get it updated soon.

**Comment by bloodmc** [comment] 2016-05-23 15:23
I'll be pushing a fix for this since repeaters in this case use the same block class but are registered as two different blocks. This should fix other redstone cases like this as well such as torches.

**Closed** 2016-05-23 16:40 UTC
