### ISSUE TITLE
Sponge and IPv6

### ISSUE THREAD

**Issue by Leeo97one** [SpongePowered/SpongeCommon#892] opened 2016-08-21 23:54 UTC
Does Sponge support IPv6 at this time?
https://forums.spongepowered.org/t/sponge-and-ipv6/14296

**Comment by ZephireNZ** [comment] 2016-08-22 10:20
https://forums.spongepowered.org/t/sponge-and-ipv6/14296

Judging by the error you posted it seems the problem is more that vanilla MC does not support IPv6, which is unfortunate. We could potentially mixin to fix these issues, however I imagine there'd be many potential places where IPv6 compat might break.

**Comment by Leeo97one** [comment] 2016-08-22 10:35
No, I've no problem with vanilla Minecraft and IPv6. I can connect easily to my server in IPv4/6 with a vanille server.

**Comment by ZephireNZ** [comment] 2016-08-22 11:07
ah, my mistake. I just looked and indeed it's our code throwing the exception. Oops :3

However there are still parts of the game that aren't build for IPv6, such as the ban-ip command.

**Comment by Leeo97one** [comment] 2016-08-22 11:35
No problem ^^
It's right that I haven't tested such commands with IPv6. I'll try.

**Comment by heni123321** [comment] 2016-08-22 12:33
/ban-ip don't work with ipv6 i have created https://bugs.mojang.com/browse/MC-97885 for the problem, but I haven't heard anything from mojang

**Comment by Minecrell** [comment] 2016-08-22 12:50
Yes, this error is actually also caused by https://bugs.mojang.com/browse/MC-97885 since Minecraft attempts to check if the first two bytes of the IPv6 address are banned. However the first 4 characters are not actually a valid IPv6 address so it fails because Sponge depends on resolving the IP address.

E.g. with `::1` (or expanded `0:0:0:0:0:0:0:1`) Minecraft gives `0` to Sponge which is not a valid IPv6 address.

**Comment by Minecrell** [comment] 2016-08-22 14:23
@Leeo97one If you need a fix for this issue, install https://github.com/Minecrell/ipv6fix/releases as plugin on your server (requires SV 102+ (tested) or SF (untested)). That should fix the error you posted here in this issue and also the MC issue @heni123321 created.

**Comment by Leeo97one** [comment] 2016-08-22 14:30
@Minecrell I'll try, thank you very much!

**Comment by Zidane** [comment] 2016-08-22 15:12
@Minecrell 

This needs to make its way into the Sponge core mixin plugin please.

**Comment by Minecrell** [comment] 2016-08-22 15:13
@Zidane Sure, I can move it once @Leeo97one can confirm that it fixes his problem.

**Comment by heni123321** [comment] 2016-08-22 15:17
@Minecrell It fixed the MC issue i linked

**Comment by Leeo97one** [comment] 2016-08-22 16:00
@Minecrell So, I've test it with SpongeVanilla 1.10.2-5.0.0-BETA-102 and everything is working well. The server start, I can connect and ban-ip with IPv6 (the IP is stored properly). Good job 👍

**Closed** 2016-08-22 17:16 UTC

**Comment by Minecrell** [comment] 2016-08-22 17:20
@Leeo97one @heni123321 Would you mind testing this again with SpongeVanilla 103? This time, the plugin should be no longer needed.

**Comment by heni123321** [comment] 2016-08-22 17:41
@Minecrell SpongeVanilla 103 works without plugin thank you
