### ISSUE TITLE
BlockEvent Chain Cause Tracking

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#223] opened 2015-10-22 06:14 UTC
Block Events triggered by players will have a cause of the player who interacted with it.
However, it only reports the owner of of the block if the cause isn't immediate. I.E. A redstone switch.

Tracking the last player/entity to interact with a block will be especially useful for event chains that happen over time.

Here is a simple world setup with a lever, two redstone, and a piston. 
https://gravityfox.net/misc/mc/world.zip
My plugin (Found here: https://github.com/gravityfox/FoxGuard) spits out the following debug info:
http://pastebin.com/CfAcnr6Y

If another player were to flip the lever instead, only the cause of the lever change will have their name. The others still point to me, since I own the blocks.

**Comment by bloodmc** [comment] 2015-10-26 07:19
@gravityfox So I was able to spend this weekend working on this issue and managed to get tracking of blocks such as redstone to work. Essentially, I am now storing the last player that notifies blocks at each position. I am currently using the following redstone map as a test case 

http://www.planetminecraft.com/project/some-redstone-creations/

So far majority of the things on this map work fine. We tested with a bunch of players. Sections that loop continuously work as well and will shift causes if a new player attempts to trigger it.

I plan on doing extensive testing this week so expect something probably by next weekend. If you want to test a build, contact me on IRC.

**Comment by JBYoshi** [comment] 2015-10-26 23:16
@bloodmc One thing to consider. Assume that a repeater is placed and set to 4 ticks, with a lever connected to the input. If Player 1 turns on the lever, then Player 2 turns the lever off *before the repeater turns on*, would the cause for the repeater turning on still be listed as Player 1?

**Comment by gabizou** [comment] 2015-11-04 21:03
@bloodmc I assume that the latest branch will end up closing this issue once merged into master?

**Closed** 2015-11-16 01:11 UTC
Labels: accepted, events
