### ISSUE TITLE
Bug "Get ImmutableSignData from ChangeBlockEvent.Break"

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeCommon#331] opened 2015-12-16 13:47 UTC
Bug "Get ImmutableSignData from ChangeBlockEvent.Break".

Code:
```
@Listener
    public void onChangeGrave(ChangeBlockEvent.Break event) {
        boolean playerCause = event.getCause().first(Player.class).isPresent();
        if (playerCause) {
            Player player = event.getCause().first(Player.class).get();
            event.getTransactions().stream().forEach((trans) -> {
                if (trans.getOriginal().getState().getType().equals(BlockTypes.WALL_SIGN)) {

                    SignManipulator dataofsign = new SignManipulator();
                    ImmutableSignData data = trans.getOriginal().getOrCreate(ImmutableSignData.class).get();
                    ArrayList<String> signLines = dataofsign.getLines(data);
                    Text msg2 = Texts.of(TextColors.GRAY, "First Line: " + signLines.get(0));
                    player.sendMessages(msg2);
                }
            });
        }
    }
}
```

Error:
```
[18:37:26] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Break$Impl to Plugin{id=grave, name=Grave, version=0.1}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:1.8.0_66]
	at io.github.azatik.grave.events.EventChangeGrave.lambda$onChangeGrave$3(EventChangeGrave.java:85) ~[EventChangeGrave.class:?]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_66]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_66]
	at io.github.azatik.grave.events.EventChangeGrave.onChangeGrave(EventChangeGrave.java:59) ~[EventChangeGrave.class:?]
	at org.spongepowered.common.event.listener.BreakListener_EventChangeGrave_onChangeGrave10.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8-2.1-DEV-93]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:247) [SpongeEventManager.class:1.8-2.1-DEV-93]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:258) [SpongeEventManager.class:1.8-2.1-DEV-93]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:111) [SpongeImpl.class:1.8-2.1-DEV-93]
	at net.minecraft.world.World.handlePostTickCaptures(SourceFile:813) [aqu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(SourceFile:87) [ih.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:111) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:305) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:531) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:447) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

Note: Tried different variants. Result - this error.
Error because of the line: `ImmutableSignData data = trans.getOriginal().getOrCreate(ImmutableSignData.class).get();`
Forum topic: https://forums.spongepowered.org/t/how-to-get-target-tileentity-from-changeblockevent-break/10252

**Comment by Aaron1011** [comment] 2015-12-16 17:57
@Azatik: I don't believe you can directly get the immutable version of a `DataManipulator` from a `DataHolder` (unless the holder is an `ImmutableDataHolder`, such as `BlockState`.

In your case, you'd want to use `trans.getOriginal().getOrCreate(SignData.class).get().asImmutable()`

**Comment by Azatik** [comment] 2015-12-16 18:14
I wrote this code:
![image](https://cloud.githubusercontent.com/assets/10154956/11849643/ac7623d4-a44a-11e5-8a9d-92207305aeee.png)

**Comment by gabizou** [comment] 2015-12-16 18:22
The problem is that an `ImmutableDataHolder`, in this case, a `BlockSnapshot` isn't able to magically define what it can and can't create. If a Sign did have sign data to begin with, it would be included in the `BlockSnapshot` already (though if it isn't then that's a bug and I know where to look).

**Comment by Aaron1011** [comment] 2015-12-16 18:30
Since this is a sign, you'd need to get the `SignData` from the `Sign` tile entity.

**Comment by Azatik** [comment] 2015-12-16 18:38
Code:
```
TileEntity tileEntity = location.getTileEntity().get();
ArrayList<String> signLines = dataofsign.getLines(tileEntity);
```
The result is the same.
Error on line:
`TileEntity tileEntity = location.getTileEntity().get();`

**Comment by simon816** [comment] 2015-12-22 23:47
The problem here is that the tile entity data is not transferred onto the `BlockSnapshot`
Using the following code:
```java
@Listener
public void onBreakSign(ChangeBlockEvent.Break event) {
    for (Transaction<BlockSnapshot> transaction : event.getTransactions()) {
        BlockSnapshot original = transaction.getOriginal();
        if (original.getState().getType().equals(BlockTypes.WALL_SIGN)) {
            System.out.println(original.getManipulators());
        }
    }
}
```
The output is `[org.spongepowered.common.data.manipulator.immutable.block.ImmutableSpongeAttachedData@87c7508d, org.spongepowered.common.data.manipulator.immutable.block.ImmutableSpongeDirectionalData@f2d3039c]`
yet no `ImmutableSignData`

I think `TileEntity.getContainers()` may be returning an empty list

**Closed** 2015-12-27 04:57 UTC
Labels: bug, data
