### ISSUE TITLE
[1.10.2] ChangeBlockEvent.Break no player cause, when tnt detonates

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeCommon#843] opened 2016-07-12 12:46 UTC
This event will contain only "Tnt primed" entity, but no player, that fired tnt.
Testing code:
```java
    @Listener
    public void changeBlockEvent(ChangeBlockEvent.Break event) {
        event.getCause().all().forEach(o -> {
            System.out.println(o.toString());
        });
        event.getCause().first(EntityTypes.PRIMED_TNT.getEntityClass()).ifPresent(explosionEvent -> {
            System.out.println("TNT WORKS");
        });
        event.getCause().first(User.class).ifPresent(user -> {
            event.getTransactions().forEach(transaction -> {
                System.out.println(user.getName());
                if(deniedBlocks.contains(transaction.getOriginal().getState().getType().getId())) {
                    transaction.setValid(false);
                    event.setCancelled(true);
                }
            });
        });
    }
```
Output:

```
[18:37:15 INFO] [STDOUT]: [org.virange.gameconrol.listeners.PlayerListeners.lambda$changeBlockEvent$0(PlayerListeners.java:28)]: EntityTNTPrimed['Block of TNT'/363, l='world', x=248,69, y=75,00, z=252,44]
[18:37:15 INFO] [STDOUT]: [org.virange.gameconrol.listeners.PlayerListeners.lambda$changeBlockEvent$0(PlayerListeners.java:28)]: EntityTNTPrimed['Block of TNT'/363, l='world', x=248,69, y=75,00, z=252,44]
[18:37:15 INFO] [STDOUT]: [org.virange.gameconrol.listeners.PlayerListeners.lambda$changeBlockEvent$1(PlayerListeners.java:31)]: TNT WORKS
```

**Comment by bloodmc** [comment] 2016-07-12 13:46
@XakepSDK Is this 1.10?

**Comment by XakepSDK** [comment] 2016-07-12 14:56
Oh, forgot:
spongevanilla-1.10.2-5.0.0-BETA-92

**Comment by gravityfox** [comment] 2016-07-12 16:21
Potential duplicate of https://github.com/SpongePowered/SpongeCommon/issues/833

**Comment by bloodmc** [comment] 2016-07-13 13:18
dupe #833

**Closed by bloodmc** 2016-07-13 13:18 UTC
Labels: 1.10, bug, events
