### ISSUE TITLE
[1.10] Events sometimes don't have player in the cause when they should

### ISSUE THREAD

**Issue by Meegooo** [SpongePowered/SpongeCommon#846] opened 2016-07-15 15:08 UTC
Examples
1. We have that structure in world (http://i.imgur.com/SZO3PWK.jpg)
   When I click the lever, two `ChangeBlockEvent.Break` events are fired. 
   First one is piston extension being removed. It doesn't have player in the cause (http://i.imgur.com/tF05TeI.png)
   Second one is sand block turning into FallingSand. That one has two causes, both are EntityFallingBlock (http://i.imgur.com/FRT9Yw4.png)
2. Just moving block with piston
   When I click the lever, `ChangeBlockEvent.Break` fires for breaking stone and placing piston extension (although I think it should be Place?). Only Piston as the cause (http://i.imgur.com/BYsKM8F.png)
   Then goes ChangeBlockEvent.Modify for piston state change. Still no player in the cause (http://i.imgur.com/LrRxpxs.png)
   Then this weird event, which I want to have nothing to do with. But for the record, still, no players (http://i.imgur.com/qsvyKEm.png)
   And finally, new stone block being placed with TWO causes, both of them are the same piston (http://i.imgur.com/0aEJEvz.png)
3. TNT
   When TNT explodes, ChangeBlockEvent.Break with bunch of transactions is fired. No Player in the cause (http://i.imgur.com/8hbcX7S.png). Tried to ignite TNT with lever and with dispenser (second one worked correctly before, i'm 100% sure)

PS. This is probably global bug with causes, but I was too lazy to test other events than ChangeBlockEvent. Maybe later.
#838, #843 and partially #833 are probably related

I used SpongeForge, if that matters

UPD:
Killing pig with TNT ignited with the lever had player in the cause.
Killing pig with TNT spawned by dispenser (activated by the lever) didn't have one (http://i.imgur.com/4UcQ3fw.png)
Killing pig with arrows from dispenser (activated with a lever). No player cause (http://i.imgur.com/U3XGYOI.png)
Killing pig with an anvil has the player cause (http://i.imgur.com/VgFCFsU.png)

**Comment by gabizou** [comment] 2016-09-04 03:42
@Meegooo if you can re-test or paste the code that you used to test for these causes. I've done all around notification handling fixes in various places the last month. Much appreciated :)

I'm pretty sure that most of these should be fixed now, but I'll get around to testing when I get a chance.

**Comment by Meegooo** [comment] 2016-09-04 06:23
1. First one works with couple slight bugs

  - when piston turns into piston extension, and when piston head is broken there's no player in the cause (http://i.imgur.com/PrCcTWB.png, http://i.imgur.com/x9MwOWF.png). 
  - when piston extension turns back into regular piston it fires event with two players in the cause. (http://i.imgur.com/uFT0RT3.png). Both are probably not a big deal

2.  - Second one also doesn't have player in the cause for piston head placing/removing. And when it didn't matter in the first case, here it is important because block was broken (http://i.imgur.com/jcoU54F.png).
 - And again, two players when piston extension is replaced with piston head (http://i.imgur.com/NYnFV3I.png).
 - There are also couple events with technical blocks that don't have player in the cause, but those are probably not important

PS. Code is simply [this](https://gist.github.com/Meegooo/959f1171fd89337e576f795785f68d7f) with breakpoints

**Comment by gabizou** [comment] 2016-09-14 15:47
@Meegooo sorry for the long wait, but this commit https://github.com/SpongePowered/SpongeCommon/commit/814979814826c9b775ce76ef38c4d2435f876b28 should resolve a lot of remaining issues with TNT disassociating block breakages.

I'll look into the piston issues as those are some corner cases that I may have to handle specially.

**Comment by modwizcode** [comment] 2016-09-15 19:06
@gabizou Does this solve https://github.com/SpongePowered/SpongeCommon/issues/729? They seemed to be related, but I can't quite determine if the fix is properly related to the problem described.

**Comment by ImMorpheus** [comment] 2017-11-23 20:53
Testing with 1.12 (bleeding branch):

1. and 2. are fixed. (They have player in the cause).
Playing around with 3. I noticed player wasn't in the cause because it was added in the context (this should be intended behavior as of the Cause refactor PR).

> Killing pig with TNT spawned by dispenser (activated by the lever) didn't have one 

Fixed

> Killing pig with arrows from dispenser (activated with a lever). No player cause
 
Fixed

#732 was also resolved.

**Closed** 2017-11-23 21:35 UTC
Labels: system: event, type: bug, version: 1.10
