### ISSUE TITLE
ItemLore is always empty

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeCommon#396] opened 2016-01-03 22:02 UTC
When trying to access an item lore of an item in player inventory its always return empty optional even if the item has lore. It seems like the itemlore is present only on items which player has in its hands.

**Comment by Aaron1011** [comment] 2016-01-12 03:00
@NeumimTo: Closing, as I'm unable to reproduce this. I believe it was fixed some some of the inventory fixes merged recently.

If you're still having this issue, please feel free to re-open this ticket, or create a new one.

**Closed by Aaron1011** 2016-01-12 03:00 UTC
