### ISSUE TITLE
Offering Keys.POWERED to a Lever fails

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeCommon#937] opened 2016-09-17 02:03 UTC
Currently, offering Keys.POWERED with either state to a lever returns FAILURE as the DataTransactionResult.

Here is the code I am using to test it,

``` java
            if (!block.supports(Keys.POWERED)) return; // Can't set this.

            block.offer(Keys.POWERED, powered);
```

It passes the test condition of whether or not it can support it.

This has been tested with both SpongeForge and SpongeVanilla bleeding as of time of this issue.

**Comment by me4502** [comment] 2016-11-04 08:27
The issue here is that no Cause is provided. Without a cause, offer only supports TileEntities.

Now, whether or not this is intentional is the question. @gabizou is this intentional? If so, this can be closed.

**Comment by ZephireNZ** [comment] 2016-11-04 09:07
Yes, it's intentional. All changes to the world need a `Cause`.

I believe this will be going away once the causetracker 2.0 gets implemented, but for now offer will require a cause for block changes.

**Comment by me4502** [comment] 2016-11-04 09:09
I'm more asking if it's intentional that tile entities don't have the restriction.

**Comment by gabizou** [comment] 2016-11-04 09:19
@me4502 since `TileEntity` changes do not provide a feasible way to mark a tile entity as being changed that is capturable with our cause tracking system, it's somewhat difficult to throw an event for every single tile entity change for every tick. Considering that in this case, the lever is a block change, it does currently require a valid `Cause` to be provided. When SpongePowered/SpongeAPI#1370 is merged, then causes will no longer be necessary to provide. 

As the javadocs already state on the API methods: making any sort of physical block change requires a `Cause`.

**Comment by me4502** [comment] 2016-11-04 09:19
Okay, thanks

**Closed by gabizou** 2016-11-04 09:19 UTC
Labels: bug, data
