### ISSUE TITLE
Execute child commands if optional argument on parent isn't present

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#447] opened 2016-01-18 21:25 UTC
I have a scenario in which a parent command accepts an optional argument, yet the children commands a) may also be present and b) need access to that parent value.

For example, imagine a plugin where a user defines a region in the world. Our plugin would define two variations of a command to be used when working with an existing region:

```
/region [name] allow [user]
/region allow [user]
```

The first specifically identifies a region by its name. The second provides no name, so our logic would have to use whichever region the player is standing in, if any.

For my experiments, using a `GenericArguments.optional` in the parent command stops all child commands from being processed. The only way to handle this currently is avoid defining any arguments specifically and to essentially take over the argument parsing.

**Comment by Zidane** [comment] 2016-02-02 23:07
@zml2008 

Lop this into your other changes please.

**Comment by ImMorpheus** [comment] 2018-01-10 20:46
Partially able to reproduce on bleeding.

What's missing in the original comment is that [name] has to be a string, otherwise there's no problem with the current system.

Example:

```
    @Listener
    public void onInit(GameInitializationEvent event) {
        CommandSpec allow = CommandSpec.builder()
                .arguments(GenericArguments.optionalWeak(GenericArguments.string(Text.of("user"))))
                .executor((src, args) -> {
                    args.<String>getOne("user").ifPresent(s -> src.sendMessage(Text.of(s)));
                    args.<Integer>getOne("name").ifPresent(s -> src.sendMessage(Text.of(s)));
                    return CommandResult.success();
                }).build();

        CommandSpec region = CommandSpec.builder()
                .arguments(GenericArguments.optionalWeak(GenericArguments.integer(Text.of("name"))))
                .child(allow, "allow")
                .build();

        Sponge.getCommandManager().register(this, region, "region");

    }
```
```

/region 1 allow notch 
notch
1


/region allow notch
notch
```

What if we try to change the parent command argument to GenericArguments.string ?

```
/region regionname allow notch
Input command regionname was not a valid subcommand!
regionname allow notch
^
Usage: /region [<name>] allow
```

A solution would be to create our own command element and use that as the argument:

```
@Plugin(id = "testtest", name = "TEST TEST", description = "TEST")
public class TestTest {

    public static Map<String, Region> m = new HashMap<>();

    @Listener
    public void onInit(GameInitializationEvent event) {
        Region r = new Region("dummyregion");
        m.put(r.getName(), r);

        CommandSpec allow = CommandSpec.builder()
                .arguments(GenericArguments.optionalWeak(GenericArguments.string(Text.of("user"))))
                .executor((src, args) -> {
                    args.<String>getOne("user").ifPresent(s -> src.sendMessage(Text.of(s)));
                    args.<Region>getOne("name").ifPresent(s -> src.sendMessage(Text.of(s.getName())));
                    return CommandResult.success();
                }).build();
        
        CommandSpec region = CommandSpec.builder()
                .arguments(GenericArguments.optionalWeak(new RegionElement(Text.of("name"))))
                .child(allow, "allow")
                .build();

        Sponge.getCommandManager().register(this, region, "region");

    }


}

class Region {

    private final String name;

    Region(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}

class RegionElement extends CommandElement {

    RegionElement(@Nullable Text key) {
        super(key);
    }

    @Nullable
    @Override
    protected Object parseValue(CommandSource source, CommandArgs args) throws ArgumentParseException {
        String arg = args.next();
        Region r = TestTest.m.get(arg);

        if (r != null) {
            return r;
        } else {
            throw args.createError(Text.of("Invalid region"));
        }

    }

    @Override
    public List<String> complete(CommandSource src, CommandArgs args, CommandContext context) {
        return null;
    }
}
```

Result:

```
/region dummyregion allow notch
notch
dummyregion


/region randomregion allow notch
Input command randomregion was not a valid subcommand!
randomregion allow notch
^
Usage: /region [<name>] allow

/region allow notch
notch
```

This could probably be closed as this is not an issue with the command API.

**Comment by ryantheleach** [comment] 2018-01-11 00:38
The difference in this vs the original post, is the original was talking about an optional, not an optionalweak.

**Comment by dualspiral** [comment] 2018-01-11 07:49
Yes, but that’s actually the fundamental difference between optional and optionalWeak, optional only works at the end of a parameter string only because it only cares about whether or not the element exists, if it exists and errors, that still throws an error. optionalWeak treats incorrect input as if the parameter did not exist, while optional would throw an error. Thus, in this scenario, `optionalWeak` would be the correct parameter to use.

You’re also getting mixed up @ImMorpheus, because the post requires a subcommand in the middle of the command, not at the beginning, or in place of. This is also possible using the `ChildCommandExecutorElement`, we do it in some of our internal commands (though I don’t remember which ones).

So, with combination of `optionalWeak` and the child element, this works. The latter bit is just ugly. I hope to make it easier in the upcoming refactor - SpongePowered/SpongeAPI#1587

**Comment by ImMorpheus** [comment] 2018-01-11 15:43
> You’re also getting mixed up ImMorpheus, because the post requires a subcommand in the middle of the command, not at the beginning, or in place of.

Then I'm missing something, my last example defines `/command [firstoptionalparam] subcommand [secondoptionalparam]`. Wasn't that what he was asking ? 

> 
> Our plugin would define two variations of a command to be used when working with an existing region:
> /region [name] allow [user]
> /region allow [user]

**Comment by ryantheleach** [comment] 2018-01-27 12:30
After discussing this with dualspiral and morph with the *current* state of the API, the original solution was would now be considered fixed with a work around of changing the syntax.

The points to note on API7 is that Optional and OptionalWeak differ.

Optional<String> will match, and offset all the arugments.
Optional<Int> wouldn't so wouldn't offset all the arguments.

CommandSpec.arguments().Executor().child()

The arguments and the children are on the 'same level' in that the builder isn't stateful in that the ordering matters, which means that the arguments belong to the fallback.

2 workarounds.

1. would be to use optionalWeak? Maybe?
2. Would be to use your own CommandElement for the region names, rather then potentially accepting an invalid string.


My resolution would be to mark this as either 'fixed' or 'invalid' but due to the age, it's hard to tell whether it was.

Either way, it's not being closed, as it's added to Dual's tracker for the Command refactor, in order to remind him to think of this while designing it.

It will be closed when Dual's Command API is merged.

**Comment by dualspiral** [comment] 2019-05-22 10:20
This will be possible in API 8 with the introduction of a new `Subcommand` element and "optional" being somewhat simplified.

Closing as it has landed on `api-8`.

**Closed by dualspiral** 2019-05-22 10:20 UTC
Labels: status: pr pending, system: command
