### ISSUE TITLE
[1.10.2] GriefPrevention plugin not reconizing flags or access rights

### ISSUE THREAD

**Issue by Deathwhitch** [SpongePowered/SpongeCommon#873] opened 2016-08-05 16:08 UTC
I posted this on the plugin page, but they pointed the finger at a being a Sponge bug (saying 1.10.2 sponge is in "bleeding" status and not his fault)

So I'm on the newest forge, newest sponge, newest pixelmon mod. Only plugins installed so far are essentials, permissionsex, and griefprevention

All seems to be working as intended but if I claim an area with griefprevention and give a user accesstust, it does not take effect. They cannot open doors and if they stand on a pressure plate it clicks about 100 times a second. If i give them build rights all works as intended. Tried to give access using the specific flag that handles interaction and same result.

**Comment by gabizou** [comment] 2016-08-05 16:12
Kinda need a description as to what's going on.

**Comment by Deathwhitch** [comment] 2016-08-05 16:18
OK I'll try to be more descriptive

I claim an area with the plugin. Once claimed I give a user 

full access (/trust)
Interaction access with doors, buttons, etc (/accesstrust)
Container and interaction access. Everything except block edits (/Containertrust)

I want user to be able to enter a building, use its buttons and doors but not break the blocks. So I use /accesstrust to give them access. Without this command the user would see "you do not have admin permission to do that" in their chat box. once I use the command the user no longer sees the chat message and the door should open. They try to open it, see no message about access, and hear the door open sound but the door remains closed. Trying to work around it i tried to use a pressure plate to activate the door, when the user stepped on it it made the "click" sound of activation you get when you step on a plate. Only it continued at a spamming rate until the user stepped off the plate. The door remains closed. If I give the user access to bock placement/destruction everything works as normal including doors and plates.

If this is still confusing to you, I can fire up my twitch stream to show you or make a video of the issue

**Comment by bloodmc** [comment] 2016-08-05 16:45
Issue is caused by 'ChangeBlockEvent.Post' being fired for every single block change event. It should only be fired when 2 or more change block events occur in a single action such as a piston moving.

**Comment by bloodmc** [comment] 2016-08-05 16:57
Talked it over with gabizou, we are going to leave the post event as is. I pushed a fix to GP which should solve your problem.

https://github.com/MinecraftPortCentral/GriefPrevention/commit/28f98be944ceff5ec1aa14e7249f74a398027b7e

**Closed by bloodmc** 2016-08-05 16:57 UTC
