### ISSUE TITLE
Broken static colored Text instances

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeCommon#6] opened 2015-04-23 22:31 UTC
It seems that whenever you build a static Text instance with a color, like the following:

``` java
private static final Text MY_TEXT = Texts.of(TextColors.RED, "My red text!");
```
the TextColor is interpreted as null somewhere, and so when the Text is sent to a player, they would see: `nullMy red text!` (uncolored).

This is a continuation from SpongePowered/Sponge#216

**Comment by Mumfrey** [comment] 2015-04-23 22:32
This should be fixed by the registry overhaul I'm working on.

**Comment by bloodmc** [comment] 2015-08-20 04:54
@gratimax is this still an issue?

**Comment by gratimax** [comment] 2015-08-20 04:59
Yes, there's been no fix (no registry overhaul, etc.) yet

**Comment by gabizou** [comment] 2015-11-07 22:31
Having experimented with the monstrous #249 Registry PR, I'm going to leave this image to give people an understanding of static class initializers:

![static](http://puu.sh/ld8tP/bbedbe3e15.png)

The issue is that plugin's main classes are being loaded far too early for any registration to take place. So early that the registry hasn't been initialized yet.

One option that @Mumfrey mentioned to me this past week was using a transformer to handle some super early registration (some things that CAN be registered as early as class loading), but it would be a "phase 2" type of thing.

**Comment by simon816** [comment] 2015-11-07 22:53
Could have an early hook maybe in the coremod or as soon as the sponge mod is constructed for things like text that aren't dependent on any particular load order

**Comment by gabizou** [comment] 2015-11-07 23:18
Ok, so did further testing, I can get texts to be usable as soon as class loading of plugins.

https://gist.github.com/gabizou/1d8d9440802c9e33982c#file-gistfile1-txt-L124
Relevant log based on the registry changes.

**Closed** 2015-11-09 03:57 UTC
Labels: bug, text
