### ISSUE TITLE
Issues with gradle dependencies on the SpongePowered repo.

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeCommon#604] opened 2016-03-21 05:51 UTC
As of a few days ago, I am receiving a 403 error when gradle attempts to download any dependencies used in the latest master from the SpongePowered repo. This has been reproduced on multiple computers, using multiple different internet connections. One of them being a Uni computer that re-images itself on restart.

Before a few days ago I was running on this commit, https://github.com/SpongePowered/SpongeForge/commit/3724235eccda4c579fd9255ab8c97602b3220f94, and it was working perfectly fine. However, I then updated and suddenly I was getting 403 errors, so I erased my gradle cache.

Erasing the gradle cache didn't do anything, as it still showed the same errors.

On the initial run through after erasing the gradle cache, it displays the 403 errors, but on the one after that, it only displays this error:

Execution failed for task ':SpongeCommon:SpongeAPI:jar'.
> Encountered duplicate path "org/spongepowered/plugin/processor/AnnotationWrapper.class" during copy operation configured with DuplicatesStrategy.FAIL

I tried to narrow this down to a single commit, so I bumped back to 3724235eccda4c579fd9255ab8c97602b3220f94, which had been working prior. That commit now has the same issue as before.

After going back further, I ended up finding that https://github.com/SpongePowered/SpongeForge/commit/339f2523c336b90c73ba66a415e5bb3042e725c8 works.

**Comment by Minecrell** [comment] 2016-03-21 16:15
Until recently (since https://github.com/SpongePowered/SpongeAPI/commit/0d59212ceb22d0ec1b3c34c39011e00bd68aa6a5) the Gradle builds used to not warn when duplicate elements are included in the JAR but rather just include all of them. This can easily cause issues at runtime, therefore it will now fail already at compile time. However, with the current configuration you should never run into duplicate class elements so there is definitely something very wrong on your side.

Are you using a recent Gradle version or the Gradle wrapper included in the Sponge projects?

**Comment by me4502** [comment] 2016-03-21 22:46
Grade wrapper included in Sponge

**Comment by Zidane** [comment] 2016-03-26 21:53
I am now hitting this issue too with a fresh Windows install and simply trying to compile. It isn't an issue on our end.

I want this fixed ASAP @Minecrell

**Comment by Zidane** [comment] 2016-03-26 22:08
Further testing shows that @Minecrell didn't correctly test this commit.

If I revert the following: https://github.com/SpongePowered/SpongeAPI/commit/0d59212ceb22d0ec1b3c34c39011e00bd68aa6a5 and run either gradle or gradlew and let that finish and THEN restore @Minecrell 's commit, all works well.

**Comment by Zidane** [comment] 2016-03-26 22:16
Scratch the last comment, it fails after the tests too with the same problem as @me4502 's original post.

**Comment by Minecrell** [comment] 2016-03-26 22:20
Reverting that commit doesn't fix the underlying problem, that somehow the classes get included twice in the JARs on your PCs, which will result in potentially malfunctioning JARs. I'm not sure why this is happening only on your PCs, however, simply reverting that commit is definitely not the way to fix it.

**Comment by Zidane** [comment] 2016-03-26 22:38
@Minecrell 

Yet reverting that commit allows me to compile and run the server without an issue. I understand the spirit of the commit but its hard for me to accept it when MY setup doesn't work from scratch when I've changed literally nothing for the last year and a half.

**Comment by Minecrell** [comment] 2016-03-27 07:47
@Zidane Then simply change the `FAIL` I added to `EXCLUDE` for now, I'll try to fix it properly once I'm back at home.

**Comment by Minecrell** [comment] 2016-04-03 17:46
Tried to reproduce this, but it none of the problems mentioned here happened for me when I built the project on a clean installation of Windows 10.

**Comment by Zidane** [comment] 2016-04-07 15:50
Closing until I see this crop up again.

**Closed by Zidane** 2016-04-07 15:50 UTC

**Comment by m0pt0pmatt** [comment] 2016-08-21 03:47
Happened for me: https://gist.github.com/m0pt0pmatt/bd8248a703be4f066ce0174605737736
