### ISSUE TITLE
PositionOutOfBoundsException: Position is out of bounds: expected in range (-30000000, 0, -30000000) to (29999999, 255, 29999999) but got (0, -1, 0)

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/SpongeCommon#188] opened 2015-10-04 23:56 UTC
http://pastebin.ubuntu.com/12686149/

**Comment by Deamon5550** [comment] 2015-10-05 00:42
Duplicate of spongepowered/Sponge#357

**Closed by Deamon5550** 2015-10-05 00:42 UTC
Labels: duplicate
