### ISSUE TITLE
BanService should provide the CommandSource of a pardon

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#436] opened 2016-01-16 18:34 UTC
When a ban is added, the `addBan` method is called which allows me to access the command source. Yet `removeBan` doesn't appear to be called when pardoning - the `pardon` methods are used directly. This prevents me from knowing the command source.

I would assume that the `removeBan` method should be the "gateway" but am not entirely familiar with the internals/mixin needs.

**Comment by Aaron1011** [comment] 2016-02-28 21:11
@viveleroi: Sorry for the delay in getting to this. Aren't you able to look up the ban object internally, based off the gameprofile or address passed in?

**Comment by viveleroi** [comment] 2016-02-29 15:48
I'm not clear on what you're advising. How would the `GameProfile` or address tell me who's performing the pardon?

**Comment by Aaron1011** [comment] 2016-03-07 21:42
@viveleroi: Ah, sorry - I thought you were asking two different questions here. I'll add a way to do that.

**Comment by Zidane** [comment] 2016-05-18 05:45
@Aaron1011 

Status update.

**Comment by ryantheleach** [comment] 2017-11-24 00:52
Due to the age and cause refactor, I am looking for people to test this on 1.12

**Comment by ryantheleach** [comment] 2017-11-24 16:26
@viveleroi @Aaron1011 If you are still interested in this / if it is still relevant, I have had @RedNesto volunteer to look into this issue, however, I was unable to give them tips on exactly what was being asked.

I've looked at the BanService and it hasn't changed since this ticket was created.

Am I correct in thinking that this issue is about trace-ability of ban causes, and finding out who was responsible for banning a player?

If so, I see 2 options, that the ban that is removed is exposed on pardon, which is an API change, or

getting the cause from the CauseStackManager?

If this was prior to any cause tracking being exposed, I can understand that the problem is (potentially) fixed if the correct causes can be made available through the CSM?

**Comment by viveleroi** [comment] 2017-11-24 16:36
Close, I was looking for the person responsible for *pardoning* a player. Causes were overhauled multiples times since this was filed, so if that data is now available through the CSM (that sounds like the recommended way to obtain it), then I think this can be closed.

**Comment by ImMorpheus** [comment] 2017-11-24 22:12
AFAIK PardonUserEvent is not implemented. 
How would you be able to obtain the command source ? 

EDIT:

@ryantheleach viveleroi's initial point is valid and not fixed by the CSM. The method we should implement PardonUserEvent into (https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/service/ban/SpongeBanService.java#L135 ) is never called.
As he noted, when a ban is removed, `pardon()` is called directly instead of `removeBan()`.
here: https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/service/ban/SpongeIPBanList.java#L93
and here: https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/service/ban/SpongeUserListBans.java#L84

Implementing the event and fixing the methods, correctly shows the player in the cause:

![pardon](https://user-images.githubusercontent.com/24737505/33225050-9a85dab4-d168-11e7-8530-c0a69cb4c0b0.png)

**Comment by ryantheleach** [comment] 2017-11-25 07:34
@ImMorpheus Sure, but the cause should also be available via the CauseStackManager directly, without the event right? (Or was this part of the 'implementing the event and fixing the methods' you described?)

Either way, if you believe you have fixed it locally, I would appreciate seeing a patch / PR depending on what you have time to submit.

For the Sponge Ban Service I would assume the responsibility lies with Sponge to throw the event, but for any other implementors, that they would be responsible for throwing the event.

---
@ImMorpheus I'm loving these detailed reports btw. Are you ever on discord / IRC?

**Comment by ImMorpheus** [comment] 2017-11-25 15:39
You mean like this ?

```
    @Listener
    public void onCommand(SendCommandEvent event) {
        System.out.println(Sponge.getCauseStackManager().getCurrentCause().first(Player.class));
    }
```

The `fixing the methods` part is needed to implement PardonUserEvent.

PR below.

**Comment by gabizou** [comment] 2018-01-09 21:57
Merged PR fixes. Thanks @ImMorpheus!

**Closed by gabizou** 2018-01-09 21:57 UTC
Labels: help wanted, status: needs-testing, system: phase-tracker
