### ISSUE TITLE
Subcommands don't show proper suggestions or hint text

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#212] opened 2015-10-18 06:24 UTC
Given some command `a` with a sub command `b` which takes arguments `c d` the following will occur:

```
/a b
<press tab>
/a b b
```

The expected behaviour is to list the options for C, not list the sub command again. Additionally, the hint text will be wrong.
Given the input:

```
/a b b
```

You will receive:

```
Input command b was not a valid subcommand!
b b
^
Usage: /a b 
```

Which does not help the user what so ever.

**Comment by gabizou** [comment] 2015-11-04 21:08
@zml2008 Anything on this?

**Comment by zml2008** [comment] 2015-11-06 05:39
this is a known issue due to how trimming is handled on command arguments. I think there's already an issue dealing with it.

**Comment by simon816** [comment] 2015-11-23 02:26
Related: #49

**Comment by ImMorpheus** [comment] 2017-11-23 17:27
Not able to reproduce using bleeding branch.

I'm not sure if this was fixed with the related issue or by #1305, but it can be closed.

**Comment by phit** [comment] 2017-11-23 21:50
I remember asking dualspiral about this a few weeks ago, what commands did you test this with @ImMorpheus ? last time I checked /sponge subcommands still had this issue

![image](https://user-images.githubusercontent.com/2097483/33189165-83cdfc70-d0a0-11e7-83a5-11760b957258.png)

**Comment by ImMorpheus** [comment] 2017-11-23 22:10
Code:

```
    @Listener
    public void onServerStart(GameStartedServerEvent event) {
        CommandSpec b = CommandSpec.builder()
                .arguments(
                        GenericArguments.onlyOne(GenericArguments.player(Text.of("player"))),
                        GenericArguments.onlyOne(GenericArguments.string(Text.of("message"))))
                .executor(((src, args) -> {
                    src.sendMessage(Text.of(args.getOne("message")));
                    return CommandResult.success();
                }))
                .build();


        CommandSpec a = CommandSpec.builder()
                .arguments(GenericArguments.none())
                .child(b, "test")
                .build();

        Sponge.getCommandManager().register(this, a,  "pr");

    }
```


"/pr test < press tab >" didn't list the subcommand again, but the options for c (player list in this case)

"/pr test test" returned "No values matching pattern test present for player!" (expected behavior)

**Comment by phit** [comment] 2017-11-23 22:13
Thanks, closing this then.

**Closed** 2017-11-23 22:12 UTC
Labels: system: command, type: bug

**Comment by ryantheleach** [comment] 2017-11-24 00:28
@ImMorpheus there is some ambiguity over whether you would be expected to do `/pr test<tab><tab>` or `/pr test<space><tab><tab>` 

Have you tested both? From memory one worked, one didn't but that may have well been addressed in my PR.

**Comment by ImMorpheus** [comment] 2017-11-24 14:46
I tested both.
I also tried with a sponge subcommand (since phit mentioned them), specifically `/sponge tps`, no issues so far.
